site_name: OTS students guide
site_author: 'lgascon1'
nav:
  - Home: index.md
  - About: about.md
  - 'Room Access':
    - 'Contacts': contact.md
    - 'Door codes': doorCodes.md
  - 'Room visits': visit.md
  - 'Data Entry': 
    - 'Staging data template': excel.md
    - 'Copying/Importing to Access': access.md
    # - 'Adding a new category': category.md
  - 'Imaging a computer': imaging.md
  - 'Vacuuming projectors': vacuum.md

repo_name: 'Github'
theme:
  name: material
  logo: 'img/TU-logo.png'

  # primary: amber
  # Light mode
  # - scheme: default
  #   toggle:
  #   icon: material/toggle-switch
  #   name: Switch to dark mode 

  # # Dark mode
  # - scheme: slate
  #   toggle: 
  #   icon: material/toggle-switch-off-outline
  #   name: Switch to light mode

markdown_extensions:
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
    
