site_name: OTS students guide
site_author: 'lgascon1'
nav:
  - Home: index.md
  - About: about.md
  - Map: map.md
  - Virtual Tour:
    - 'FAQ': VTFAQs.md
    - 'Before heading out':
      - 'Check the schedule': visit.md
      - 'Doors': doorCodes.md
    - 'While at the room':
      - 'Collections' : collections.md
      - 'Equipment' : equipment.md
    - 'Editing Photos': photoEdit.md
    - 'Data Entry':
      - 'Staging data template': excel.md
      - 'Working with Access': access.md
    # TODO: Create a page for adding category to the database
    # - 'Adding a new category': category.md
  - Imaging a computer: imaging.md
  - Solstice Pod:
    - 'Instalation/Replacement': solstice.md
    - 'Maintenance': fixing_solstice.md
  - Vacuuming projectors: vacuum.md
  - Summer room checks: summer.md
  - Quality Assurance : qa.md
  - Mapping Network Drives: networkDrive.md
  - Equipment:
    - Microphones: microphones.md
    - Cameras: cameras.md
    - Control panels: panels.md
    - Projectors: projectors.md

repo_name: 'Github'
theme:
  name: material
  icon:
    logo: material/Rocket
  features:
    - toc.follow
    - content.tabs.link
  palette:
    primary: white
  # primary: amber
  # Light mode
  # - scheme: default
  #   toggle:
  #   icon: material/toggle-switch
  #   name: Switch to dark mode 

  # # Dark mode
  # - scheme: slate
  #   toggle: 
  #   icon: material/toggle-switch-off-outline
  #   name: Switch to light mode

markdown_extensions:
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - md_in_html

