site_name: OTS students guide
site_author: 'lgascon1'
nav:
  - Home: index.md
  - About: about.md
  - Map: map.md
  - Virtual Tour Tasks:
    - 'FAQ': VTFAQs.md
    - 'Room Access':
      - 'Doors': doorCodes.md
    - 'Room visits': 
      - 'Collections' : collections.md
      - 'Equipment' : equipment.md
    - 'Editing Photos': photoEdit.md
    - 'Data Entry': 
      - 'Staging data template': excel.md
      - 'Working with Access': access.md
    # - 'Adding a new category': category.md
  - 'Imaging a computer': imaging.md
  - 'Installing Solstice Pod': solstice.md
  - 'Vacuuming projectors': vacuum.md
  - 'Summer room checks': summer.md
  - 'Quality Assurance' : qa.md
  - 'Mapping Network Drives': networkDrive.md

repo_name: 'Github'
theme:
  name: material
  logo: '/img/8713174.png'
  features:
    - toc.follow
  palette:
    primary: white
  # primary: amber
  # Light mode
  # - scheme: default
  #   toggle:
  #   icon: material/toggle-switch
  #   name: Switch to dark mode 

  # # Dark mode
  # - scheme: slate
  #   toggle: 
  #   icon: material/toggle-switch-off-outline
  #   name: Switch to light mode

markdown_extensions:
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - md_in_html
    
