site_name: OTS students guide
site_author: 'lgascon1'
nav:
  - Home: index.md
  - About: about.md
  - Virtual Tour Tasks:
    - 'FAQ': VTFAQs.md
    - 'Before the visit': visit.md
    - 'Room Access':
      - 'Doors': doorCodes.md
    - 'While at the room':
      - 'Collections' : collections.md
      - 'Equipment' : equipment.md
    - 'Editing Photos': photoEdit.md
    - 'Instructions': instructions.md
    - 'Data Entry':
      - 'Staging data template': excel.md
      - 'Working with Access': access.md
  - Imaging a computer: imaging.md
  - Solstice Pod:
    - 'Instalation/Replacement': solstice.md
    - 'Maintenance': fixing_solstice.md
  - Vacuuming projectors: vacuum.md
  - Summer room checks: summer.md
  - Quality Assurance : qa.md
  - Mapping Network Drives: networkDrive.md
  - Fusion Offline Rooms: offline_fusion.md
  - Equipment:
    - Microphones: microphones.md
    - Cameras: cameras.md
    - Control panels: panels.md
    - Projectors: projectors.md

repo_name: 'Github'
theme: 
  name: material
  icon:
    logo: material/Rocket
  features:
    - toc.follow
    - content.tabs.link
  palette:
    # Light mode
    - scheme: default
      primary: amber
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode 

    # Dark mode
    - scheme: slate
      primary: amber
      accent: black
      toggle: 
        icon: material/brightness-7
        name: Switch to light mode
extra:
  generator: false
copyright: CCLT Student Employee Documentation
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - mdx_truly_sane_lists
  - md_in_html
plugins:
  - offline